# Generated by Django 5.1.7 on 2025-03-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='Photo',
        ),
    ]
