# Generated by Django 5.1.7 on 2025-03-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='posts/media/uploads/'),
        ),
    ]
