# Generated by Django 5.1.7 on 2025-03-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Photo',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
