# Generated by Django 5.1.7 on 2025-03-15 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 15, 10, 36, 23, 127199, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
